- name: Build 
  hosts: reverse-proxy_dev
  serial: 1
  vars_files:
    - vars.yaml
    - vault.yaml
  tasks:
    - name: Run install tasks
      import_tasks: tasks/install.yaml

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: true

