- name: Build 
  hosts: prod
  serial: 1
  vars_files:
    - vars.yaml
    - vault.yaml
  tasks:                
    - name: Generate nginx config files on server
      import_tasks: tasks/generate-sites.yaml

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: true
  