- name: Update haproxy config file
  hosts: dev
  serial: 1
  vars_files:
    - vars.yaml
    - vault.yaml
  tasks:                
    - name: Generate and copy config files
      import_tasks: tasks/generate-configs.yaml
